import Steps from "./components/Steps";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function BookingLayout({ children }) {
    return (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-4 items-center justify-items-center min-h-[80vh]">
        <Steps />
            {children}
        </div>
    );
}
